// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCPRGPvprNv8HWBesFec-UEVTNib3eyjRQ',
    appId: '1:376956523739:web:a53fde82bee7c71ea868fe',
    messagingSenderId: '376956523739',
    projectId: 'chatapp-6d404',
    authDomain: 'chatapp-6d404.firebaseapp.com',
    storageBucket: 'chatapp-6d404.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBx91w4BHlQfTrCEqN7ohx1ARndBLAmDQA',
    appId: '1:376956523739:android:8ffbfd21805554d3a868fe',
    messagingSenderId: '376956523739',
    projectId: 'chatapp-6d404',
    storageBucket: 'chatapp-6d404.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBxDXqLknvElI9zZZm-Ppd0GWdMHC3MqWY',
    appId: '1:376956523739:ios:91c1668c90a3d1ada868fe',
    messagingSenderId: '376956523739',
    projectId: 'chatapp-6d404',
    storageBucket: 'chatapp-6d404.appspot.com',
    iosBundleId: 'com.example.minimalChatApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBxDXqLknvElI9zZZm-Ppd0GWdMHC3MqWY',
    appId: '1:376956523739:ios:91c1668c90a3d1ada868fe',
    messagingSenderId: '376956523739',
    projectId: 'chatapp-6d404',
    storageBucket: 'chatapp-6d404.appspot.com',
    iosBundleId: 'com.example.minimalChatApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCPRGPvprNv8HWBesFec-UEVTNib3eyjRQ',
    appId: '1:376956523739:web:e9e36e0564c47162a868fe',
    messagingSenderId: '376956523739',
    projectId: 'chatapp-6d404',
    authDomain: 'chatapp-6d404.firebaseapp.com',
    storageBucket: 'chatapp-6d404.appspot.com',
  );
}
